### ISSUE TITLE
scoped storage for Images in Android 10

### ISSUE THREAD

**Issue by mrjones-plip** [dimagi/rd-toolkit#47]
Filing this ticket on @latin-panda's behalf after having a chat with @ctsims:

We've gotten rd-toolkit to successfully access  images taken with the app in  Android 5.1, 6, 8, 9 and 11 (our app supports Android 4.1 to 11). However, when testing in Android 10  (Samsung S9, Samsung A01, Pixel 1 & One Plus 6), an `access denied` exception is thrown when capturing an image.

We're using the context's file descriptor to access the files, so far it works great in all versions (5.1 to 11) except Android 10. Looking further into this, Android introduced the scoped storage in Android 10 where it uses the `content://` schema in the file's URI.

Checking the file's URI in the Android 10 by using native's pick action, we confirmed that Android is using the `content://` schema in the devices, but the rd-toolkit is returning `file://` schema. 

We are wondering if you can please add support for `content://` shema in Android 10 + in rd-toolkit?

**Comment by mrjones-plip** [comment]
@ctsims  responded to @latin-panda with:

So I believe the toolkit currently is configured to use `content://` providers since this pull request but I think we only configured it to be the default on 11+  to provide the broadest compatibility. 

We have a couple of options. I left provisions in the code to somewhat easily send a config flag for forcing the use of content providers, but am also open to bumping the default down to 10+ if that makes more sense.

In the meantime it would be useful to know whether forcing this flag to true  on a local build makes things work correctly for you to confirm the way forward.

**Comment by mrjones-plip** [comment]
From here I'll let @latin-panda and @ctsims  chat so I can get out of their way!

CC @garethbowen

**Comment by latin-panda** [comment]
Thanks @mrjones-plip!

@ctsims I've tested by [bumping down to 10+](https://github.com/dimagi/rd-toolkit/blob/a8318ee1ad63d7579c4fcf29a09f90313de20cc8/app/src/main/java/org/rdtoolkit/interop/Interfaces.kt#L61) and by [setting the flag in true](https://github.com/dimagi/rd-toolkit/blob/a8318ee1ad63d7579c4fcf29a09f90313de20cc8/app/src/main/java/org/rdtoolkit/ui/capture/CaptureActivity.java#L373) both resolve the issue in Android 10 (tested with S9)

The bumping down to 10+ is a fast and clean option, any app in Google's Playstore will have to support [Android 11 by November](https://developer.android.com/distribute/best-practices/develop/target-sdk) which also will need to support the new file schema since it's enforced in Android 11. 

However, if there are still concerns about bumping down, then setting the flag by using a configuration property in the Capture Intent's extra would work as well. Because of the tool we're using to connect CHT with RDToolkit, we configure the intent manually and can send the flag through extras.

Thanks!

**Comment by ctsims** [comment]
Hi @latin-panda,

That makes sense. We didn't pick the Android 10/11 boundary particularly carefully, so I think that enforcing the content provider path on Android 10 will make the most sense for now. 

The alternate path would be adding it to the intent as a flag and then having the support library check the calling app for its build target and selectively using the flag for Android 10 OS apps built against Android 11, but that effort seems unwarranted given the points you've mentioned.

I'll kick off a change on this today and update the Open Testing stream on the Play Store with a new build for testing.

**Comment by ctsims** [comment]
@latin-panda This should be in the latest Open Testing beta on the Play Store 0.9.8. If you can confirm the pre-release looks good, I'll go ahead and close this out. Thanks!

**Comment by latin-panda** [comment]
@ctsims Thank you so much for the fast fix!
I've tested v0.9.8 in Android 10 (Samsung Note 9) and Android 11 (Samsung S20) and both phones are working fine with the `content://` we can retrieve the images.

**Comment by ctsims** [comment]
Great to hear. Let me know if your team needs anything else.

**Comment by mrjones-plip** [comment]
Thanks again for the speedy turn around @ctsims  - @latin-panda already confirmed, so safe to close this, but in testing our integration just now, I was happy to see the image returned back to our app! \o/

**Comment by mrjones-plip** [comment]
@ctsims - what's the release schedule for this fix to the play store?  We're happy to instruct folks to install and then sign up for the public beta to get `0.9.8`, but a GA release would be easier.  Thanks!

**Comment by ctsims** [comment]
Hi @mrjones-plip .

I promoted 0.9.8 to production yesterday, so it should now be the live public release.

**Comment by mrjones-plip** [comment]
Thanks so much @ctsims! I already see [it showing up](https://play.google.com/store/apps/details?id=org.rdtoolkit&hl=en_US&gl=US) \o/
